# FORGE CONFIG (DO NOT REMOVE!)
include forge-conf/darkroom.jerome-arfouche.ca/before/*;

server {
    http2 on;
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name darkroom.jerome-arfouche.ca;
    server_tokens off;
    root /home/forge/darkroom.jerome-arfouche.ca/dist;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # FORGE SSL (DO NOT REMOVE!)
    ssl_certificate /etc/nginx/ssl/darkroom.jerome-arfouche.ca/2794764/server.crt;
    ssl_certificate_key /etc/nginx/ssl/darkroom.jerome-arfouche.ca/2794764/server.key;
}

# FORGE CONFIG (DO NOT REMOVE!)
include forge-conf/darkroom.jerome-arfouche.ca/after/*;